# Generated by Django 5.0.4 on 2024-04-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Администратор'),
        ),
        migrations.AddField(
            model_name='customusers',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Суперпользователь'),
        ),
    ]
