# Generated by Django 5.0.4 on 2024-04-22 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sklads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название склада')),
                ('adres', models.CharField(max_length=256, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
            },
        ),
        migrations.CreateModel(
            name='Tehnika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Вид техники')),
                ('sklad', models.ForeignKey(blank=True, default=None, max_length=256, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.sklads', verbose_name='На складе')),
            ],
            options={
                'verbose_name': 'Вид техники',
                'verbose_name_plural': 'Вид техники',
            },
        ),
        migrations.CreateModel(
            name='Edinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seriniy', models.CharField(max_length=256, verbose_name='Сериный нмоер')),
                ('brand', models.CharField(max_length=256, verbose_name='Производитель')),
                ('modelmodel', models.CharField(max_length=256, verbose_name='Модель')),
                ('sklad', models.ForeignKey(blank=True, default=None, max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.sklads', verbose_name='Склад')),
                ('title', models.ForeignKey(blank=True, default=None, max_length=256, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.tehnika', verbose_name='Вид техники')),
            ],
            options={
                'verbose_name': 'Единица',
                'verbose_name_plural': 'Единицы',
            },
        ),
    ]
