# Generated by Django 5.0.4 on 2024-04-22 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tehnika',
            name='sklad',
        ),
        migrations.AlterField(
            model_name='edinica',
            name='seriniy',
            field=models.CharField(max_length=256, verbose_name='Сериный номер'),
        ),
    ]
