# Generated by Django 5.0.4 on 2024-04-22 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_remove_tehnika_sklad_alter_edinica_seriniy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etazh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Этаж')),
            ],
            options={
                'verbose_name': 'Этаж',
                'verbose_name_plural': 'Этажи',
            },
        ),
        migrations.AddField(
            model_name='edinica',
            name='kabinet',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Номер кабинета'),
        ),
        migrations.AddField(
            model_name='edinica',
            name='lico',
            field=models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='Ответственный'),
        ),
        migrations.AddField(
            model_name='edinica',
            name='remont',
            field=models.BooleanField(default=False, null=True, verbose_name='В ремонте'),
        ),
        migrations.AddField(
            model_name='edinica',
            name='etazh',
            field=models.ForeignKey(blank=True, default=None, max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.etazh', verbose_name='Этаж'),
        ),
    ]
