# Generated by Django 5.0.4 on 2024-04-22 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_etazh_sklad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etazh',
            name='sklad',
        ),
    ]
