# Generated by Django 5.0.4 on 2024-04-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_remove_etazh_sklad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sklads',
            name='adres',
        ),
        migrations.AlterField(
            model_name='sklads',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Адрес'),
        ),
    ]
