# Generated by Django 5.0.4 on 2024-04-22 07:18

import storage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_remove_sklads_adres_alter_sklads_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edinica',
            name='id',
        ),
        migrations.AddField(
            model_name='edinica',
            name='invent',
            field=storage.models.SixDigitAutoField(default=100000, primary_key=True, serialize=False, verbose_name='Номер инвентаризации'),
            preserve_default=False,
        ),
    ]
