# Generated by Django 5.0.4 on 2024-04-22 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0009_etazh_sklad_kabinet_alter_edinica_kabinet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etazh',
            name='sklad',
        ),
        migrations.RemoveField(
            model_name='kabinet',
            name='etazh',
        ),
    ]
