# Generated by Django 5.0.4 on 2024-04-22 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0010_remove_etazh_sklad_remove_kabinet_etazh'),
    ]

    operations = [
        migrations.AddField(
            model_name='etazh',
            name='sklad',
            field=models.ForeignKey(blank=True, default=None, max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.sklads', verbose_name='Склад'),
        ),
        migrations.AddField(
            model_name='kabinet',
            name='etazh',
            field=models.ForeignKey(blank=True, default=None, max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.etazh', verbose_name='Этаж'),
        ),
    ]
